In [1]:
import numpy as np

In [ ]:
n1 = np.array([1, 2, 3, 4, 5]) # 1-D array
print(n1)
print(n1.size)
print(type(n1))
print(n1.ndim)

# All Execution are part of EDA

[1 2 3 4 5]
5
<class 'numpy.ndarray'>
1


In [6]:
n2 = np.array([[1, 2, 3, 4], [2, 3, 4, 5]])
print(n2)
print(n2.size)
print(type(n2))
print(n2.ndim)

[[1 2 3 4]
 [2 3 4 5]]
8
<class 'numpy.ndarray'>
2


In [ ]:
n3 = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(n3)
print(n3.size)
print(type(n3))
print(n3.ndim)

# In case you 3D array then must be convert into 2D array
# then model train

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
9
<class 'numpy.ndarray'>
3


In [9]:
n4 = np.array([[[[1, 2], [3, 4], [5, 6],[7, 8]]]])
print(n4)
print(n4.size)
print(type(n4))
print(n4.ndim)

[[[[1 2]
   [3 4]
   [5 6]
   [7 8]]]]
8
<class 'numpy.ndarray'>
4


In [2]:
n4 = np.array(list(map(int, input("Enter elements").split())))
print(n4)

[9 0]


In [ ]:
n = int(input("Enter number of elements :"))
n5 = np.array([int(input()) for i in range(n)])
print(n5)
    
# Important Code

[2 2 2]


In [12]:


row = int(input("Enter number of Rows: "))
column = int(input("Enter number of Columns: "))
t = []
for i in range(row):
    t1 = []
    for j in range(column):
        v = int(input("Enter element: "))
        t1.append(v)
    t.append(t1)
n = np.array(t)
print(n)

ValueError: invalid literal for int() with base 10: ''

In [13]:
z = np.zeros(4)
print(z)

[0. 0. 0. 0.]


In [14]:
z2 = np.zeros((4, 4))
print(z2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
y = np.ones(4)
print(y)

[1. 1. 1. 1.]


In [16]:
t3 = np.eye(3)
t3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#  Indexing and Slicing

a = np.array([1, 2, 3, 4, 5])
print(a[1])

b = np.array([[1, 3, 4], [3, 5, 6]])
print(b[1][2])

c = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(c[0][1][1])

print(a[1:3])
print(b[0:1, 1:2])


print(c[0, 1])

2
6
5
[2 3]
[[3]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]


In [39]:
print(c[0, 0, 2])
print(c[0, 1, 1])
print(c[0, 2, 0])

3
5
7


In [40]:
a1 = np.array([1, 2, 3, 4, 5])
print(a1.shape)

(5,)


In [42]:
a2 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(a2.shape)

(9,)


In [43]:
s = a2.reshape(3, 3)

In [44]:
print(a2)

[1 2 3 4 5 6 7 8 9]


In [45]:
print(s)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [49]:
x = np.arange(1, 9)
y = x.reshape(2, 2, 2)
print(y)
print(y.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3


In [50]:
a = np.arange(1, 28)
y = a.reshape(3, 3, 3)
print(y)
print(y.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]
3


In [51]:
a = np.array([12, 34, 56, 78, 88, 33])
x = a + 2
y = a * 2

print(x)
print(y)

[14 36 58 80 90 35]
[ 24  68 112 156 176  66]


In [58]:
a1 = np.array([[1345, 2555, 3444, 4333], [5333, 633, 733, 833]])
a2 = np.array([11, 22, 33, 44])
z1 = a1 + a2
z2 = a1 * a2
z3 = a1 / a2
print(z1)
print(z3)

[[1356 2577 3477 4377]
 [5344  655  766  877]]
[[122.27272727 116.13636364 104.36363636  98.47727273]
 [484.81818182  28.77272727  22.21212121  18.93181818]]
